

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5000/eureka/
spring:
  application:
    name: points-mall-service
server:
  port: 5003
