spring:
  application:
    name: gateway-route

  cloud:
    gateway:
      httpclient:
        connect-timeout: 500
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true

          #下面的routes 可以不写，访问规则：http://localhost:5001/POINTS-MALL-SERVICE/mall/points-user
          #【http://gateway_ip://gateway_port/大写的service名字/访问资源路径  】

          #如果写了routes: 则 支持任何路径的：http://localhost:5001/x/user/getUser
      routes:
        - id: userinfo-service
          uri: lb://userinfo-service
          predicates:
            - Path=/*/**
          filters:
            - StripPrefix=1

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 5001

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5000/eureka/